version: '3.9'

services:
  server:
    build:
      context: ./
      dockerfile: docker/server.dockerfile
      args:
        - VER_NODE
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:5000"
    volumes:
      - modules_server:/usr/src/app/node_modules # prevent binding of host node_modules
      - ./server:/usr/src/app
    env_file: .env
    depends_on:
      - postgres
      - redis
      - worker

  worker:
    build:
      context: ./
      dockerfile: docker/worker.dockerfile
      args:
        - VER_NODE
    restart: unless-stopped
    volumes:
      - modules_worker:/usr/src/app/node_modules # prevent binding of host node_modules
      - ./server:/usr/src/app
    env_file: .env

  postgres:
    image: ${VER_POSTGRES}
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  redis:
    image: ${VER_REDIS}
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data

volumes:
  modules_server: {}
  modules_worker: {}
  pgdata: {}
  redisdata: {}
